// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD8GVQtp0C-cFnLCSZUbqt76fboJa6NyY',
    appId: '1:267072187037:android:d89baad5cfe9f9036a4274',
    messagingSenderId: '267072187037',
    projectId: 'atomfit-8df11',
    storageBucket: 'atomfit-8df11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDawZmS5H1UMD9zAGWQ4ijxsqE9lt8M8Bk',
    appId: '1:267072187037:ios:47116718b031defa6a4274',
    messagingSenderId: '267072187037',
    projectId: 'atomfit-8df11',
    storageBucket: 'atomfit-8df11.firebasestorage.app',
    iosClientId: '267072187037-udk583ureb2jvanlghamikqiems97dnc.apps.googleusercontent.com',
    iosBundleId: 'com.atomicity.atomfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDawZmS5H1UMD9zAGWQ4ijxsqE9lt8M8Bk',
    appId: '1:267072187037:ios:fee935ce94eb76496a4274',
    messagingSenderId: '267072187037',
    projectId: 'atomfit-8df11',
    storageBucket: 'atomfit-8df11.firebasestorage.app',
    iosClientId: '267072187037-9c5svindfp05o5ho999qhi0182npe0n7.apps.googleusercontent.com',
    iosBundleId: 'com.xraph.plugin.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh0EDmOCjNSSgUe2CFVtrnp7pKIyEsYX8',
    appId: '1:267072187037:web:5f0bd6bdbbf525046a4274',
    messagingSenderId: '267072187037',
    projectId: 'atomfit-8df11',
    authDomain: 'atomfit-8df11.firebaseapp.com',
    storageBucket: 'atomfit-8df11.firebasestorage.app',
    measurementId: 'G-3GKQPFHP9N',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgw_w3uCMGmM3j_6tQvNz1loQSKCZIbLg',
    appId: '1:778349258018:web:de32625723699d1751717b',
    messagingSenderId: '778349258018',
    projectId: 'atomkart-ef1c5',
    authDomain: 'atomkart-ef1c5.firebaseapp.com',
    storageBucket: 'atomkart-ef1c5.firebasestorage.app',
  );

}